### ISSUE TITLE
Site not readable on Firefox/Edge

### ISSUE THREAD

**Issue by Prophet-Phoenix** [rslavey/TVRatings#1]
Hi Randy,
i really like whattowatchontv since i discovered on reddit. I dont know if you still maintain this project, but on Win 10 Firefox and Edge, the css seems broken:
![grafik](https://github.com/rslavey/TVRatings/assets/82598183/d7dd60eb-4ea7-465c-b9f1-850df75726fd)

System: Recent version of MS Edge on Win 10, without extensions. I have a network wide adblocker via dns though (oisd.nl list - though disabling it doesn't change the issue).
Steps to reproduce: visit whattowatchon.tv, browse, try to select a series from search

wkr

**Comment by rslavey** [comment]
Ah, thanks for letting me know. I had trouble finding the root cause because I'm on dark mode. I was relying on the browser to set the background color to black without considering someone might be on light mode, which sets it to white. I will update the site to statically set the background color. Thanks for letting me know.

**Comment by rslavey** [comment]
This has been resolved. Thanks again for reporting the issue. Glad you're enjoying the site.
